services:

  # MySQL database service
  mysql:
    image: mysql:8.0
    container_name: mysql

    # Connect MySQL to the application network
    networks:
      - bankapp-network

    # Host:Container port mapping
    ports:
      - "3306:3306"

    # Persist MySQL database data
    # Data remains even if the container is recreated
    volumes:
      - bankapp-data:/var/lib/mysql

    environment:
      # MySQL root password
      MYSQL_ROOT_PASSWORD: Test@123

      # Database created during first initialization
      MYSQL_DATABASE: bankappdb

    # Check whether MySQL is ready to accept connections
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s


  # Spring Boot BankApp service
  bankapp:
    # Build the application image using the Dockerfile
    build: .
    container_name: bankapp

    # Connect BankApp to MySQL and Ollama
    networks:
      - bankapp-network

    # Host:Container port mapping
    ports:
      - "8080:8080"

    environment:
      # Use Compose service name as the hostname
      MYSQL_HOST: mysql

      MYSQL_PORT: 3306
      MYSQL_DATABASE: bankappdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Test@123

      # Ollama API endpoint inside Docker network
      OLLAMA_URL: http://ollama:11434


  # Ollama AI service
  ollama:
    image: ollama/ollama
    container_name: ollama

    # Allow BankApp to communicate with Ollama
    networks:
      - bankapp-network

    # Ollama API port
    ports:
      - "11434:11434"

    # Persist downloaded AI models
    volumes:
      - ollama:/root/.ollama


# Custom network for communication between services
networks:
  bankapp-network:


# Named volumes for persistent application data
volumes:
  bankapp-data:
  ollama:

# After running container install tiney inside ollama container to make live AI in the application using below command
# docker exec -it <container_ID> ollama run tinyllama
#
# After starting the containers, download an AI model:
#
# docker exec -it ollama ollama pull tinyllama
#
# Check installed models:
#
# docker exec -it ollama ollama list
#
# Test the AI model:
#
# docker exec -it ollama ollama run tinyllama