# Use Java 21 JDK image
# JDK is required because Maven compiles the Java application
FROM eclipse-temurin:21-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the application source code into the container
COPY . .

# Make Maven Wrapper executable and build the application
# -DskipTests → skip test execution
# -B          → run Maven in batch/non-interactive mode
RUN chmod +x mvnw && ./mvnw clean package -DskipTests -B

# Verify the files generated by the build
# Useful for troubleshooting the JAR location/name
RUN ls -la

# Start the Spring Boot application
# target/*.jar automatically matches the generated JAR file
ENTRYPOINT ["sh", "-c", "java -jar target/*.jar"]